title: Logan's Blog
author: Logan Rouleau
email: lrouleau@ualberta.ca
description: >
  Thoughts from a runner in Vancouver.
# TODO: Remove baseurl property or change it to '/'
baseurl: "/"
url: "https://loganrouleau.com"
permalink: pretty

# Build settings
markdown: kramdown

# Syntax highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

navigation_internal:
  - title: About
    url: /about

navigation_external:
  - title: Strava
    url: https://www.strava.com/athletes/19307941
  - title: GitHub
    url: https://github.com/loganrouleau

# Sass settings
sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
