title: Logan's Blog
author: Logan Rouleau
email: lrouleau@ualberta.ca
description: >
  Thoughts from a runner in Vancouver.
baseurl: "/"
url: "http://loganrouleau.com"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed

navigation:
  - title: About
    url: /about
  - title: GitHub
    url: https://github.com/loganrouleau

# Sass settings
sass:
    sass_dir: _scss
    style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
